name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  # Reduce compile time and cache size.
  RUSTFLAGS: -Dwarnings -Zshare-generics=y -Zthreads=0
  # Use the same Rust toolchain across jobs so they can share a cache.
  toolchain: nightly-2026-01-22

jobs:
  build-web:
    name: Build web
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: echo "RUSTFLAGS=${RUSTFLAGS:+$RUSTFLAGS }--cfg getrandom_backend=\"wasm_js\"" >> "${GITHUB_ENV}"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.toolchain }}
          targets: wasm32-unknown-unknown

      - name: Restore Rust cache
        id: cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: web-ci
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install build dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev

      - name: Check web
        run: cargo check --config 'profile.web.inherits="dev"' --profile ci --no-default-features --features dev --target wasm32-unknown-unknown
